spring:
  profiles:
    active: dev

person:
  name: zhangsan${random.uuid}
  age: ${random.int}
  boss: false
  birth: 2017/12/12
  map: {k1: v1,k2: v2}
  list:
    - zhangsan
    - lisi
    - wanggang
  dog:
    name: ${person.name}_dog
    age: 2